### ISSUE TITLE
Typo in pyproject.toml

### ISSUE THREAD

**Issue by oleicht** [MarcoGorelli/cookiecutter-polars-plugins#2]
https://github.com/MarcoGorelli/cookiecutter-polars-plugins/blob/504bcb6eaf4792ca79040dd9730d955cd3272eea/%7B%7B%20cookiecutter.project_slug%20%7D%7D/pyproject.toml#L2

I believe it should be `polars>=0.20.6` - 0.26.0 isn't released yet.

**Comment by MarcoGorelli** [comment]
thank you so much @oleicht ! you're right

**Comment by MarcoGorelli** [comment]
done
