### ISSUE TITLE
Issue with `returns_scalar` for `register_plugin`

### ISSUE THREAD

**Issue by bomtall** [MarcoGorelli/cookiecutter-polars-plugins#8]
Hello!

I tried following the instructions but I get the following error (I think I have setup the environment correctly):

```
(.venv) josie@...:~/code/cookiecutter-polars-plugins/minimal_plugin$ python run.py 
Traceback (most recent call last):
  File "/home/josie/code/cookiecutter-polars-plugins/minimal_plugin/run.py", line 7, in <module>
    result = df.with_columns(pig_latin = pig_latinnify('english'))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josie/code/cookiecutter-polars-plugins/minimal_plugin/minimal_plugin/__init__.py", line 22, in pig_latinnify
    return register_plugin(
           ^^^^^^^^^^^^^^^^
TypeError: register_plugin() missing 1 required keyword-only argument: 'returns_scalar'
```

Adding `returns_scalar=False` in https://github.com/MarcoGorelli/cookiecutter-polars-plugins/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/%7B%7B%20cookiecutter.project_slug%20%7D%7D/__init__.py#L22-L27 seems to fix the issue

**Comment by MarcoGorelli** [comment]
thanks @bomtall! that should fix it

cc @thomasjpfan just FYI (no blame!)

**Comment by MarcoGorelli** [comment]
it should be fine if you try again now
